BEGIN
    BEGIN
        DBMS_SCHEDULER.DROP_JOB(job_name => 'CLEANUP_EXPIRED_GAMES_JOB', force => TRUE);
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;

    BEGIN
        DBMS_SCHEDULER.DROP_JOB(job_name => 'DAILY_CHALLENGE_JOB', force => TRUE);
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
END;
/

DROP PACKAGE GAME_MANAGER_PKG;

DROP TABLE MOVE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE GAMES CASCADE CONSTRAINTS;
DROP TABLE DAILY_CHALLENGES CASCADE CONSTRAINTS;
DROP TABLE USER_IMAGES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

DROP SEQUENCE MOVE_HISTORY_SEQ;
DROP SEQUENCE GAMES_SEQ;
DROP SEQUENCE DAILY_CHALLENGES_SEQ;
DROP SEQUENCE USER_IMAGES_SEQ;
DROP SEQUENCE USERS_SEQ;

COMMIT;